add search spinner while waiting for search to run
LD4P/sinopia_editor pull request #2567
Opened 2020-09-30 18:47 UTC by peetucket

## Why was this change made?

Fixes #2182 

Note, the spinner text for "results loading" is currently in a span that only shows for screen readers.
This is how it looks:

![spinner](https://user-images.githubusercontent.com/47137/94726817-9dff9700-0312-11eb-90e5-f145738de66a.gif)

To do:

- [ ] timeout after 30 seconds

## How was this change tested?

Localhost browser

## Which documentation and/or configurations were updated?

None

2020-09-30 23:35 UTC, peetucket commented
Using this technique for timeing out the fetch calls: https://github.com/whatwg/fetch/issues/951#issuecomment-541369940

2020-10-02 21:09 UTC, jermnelson requested changes
Looks good but needs a feature test.

2020-10-02 21:48 UTC, peetucket commented
Updated a search feature test to look for the spinner

2020-10-02 21:59 UTC, jermnelson approved these changes

2020-10-02 22:04 UTC, merged