Remember resource and template search state
LD4P/sinopia_editor pull request #2570
Opened 2020-09-30 22:37 UTC by mjgiarlo

Fixes #2227

See screencast to watch feature in action:

![Peek 2020-09-30 15-35](https://user-images.githubusercontent.com/131982/94746947-b7b0d680-0332-11eb-87ba-20cfb5bddb0f.gif)

## Why was this change made?

To prevent catalogers from having to re-type searches for resources and templates over and over again

## How was this change tested?

CI and in browser locally

## Which documentation and/or configurations were updated?

None

2020-10-01 01:48 UTC, justinlittman requested changes
Seems like the authority should also be sticky.

2020-10-01 22:18 UTC, mjgiarlo commented
@justinlittman :speech_balloon: 
> Seems like the authority should also be sticky.
done!

2020-10-01 22:19 UTC, mjgiarlo commented on cypress/integration/end2end.spec.js
> -            .type('resourceTemplate:bf2:WorkTitle')
No need to type it in again because it's still there.

2020-10-01 22:19 UTC, mjgiarlo commented on cypress/integration/leftNav.spec.js
> -          .type('resourceTemplate:testing:uber1')
Don't type it in because it's already there.

2020-10-01 22:20 UTC, mjgiarlo commented on src/components/search/Search.jsx
> -  const fetchQASearchResults = (queryString, uri, startOfRange) => dispatch(fetchQASearchResultsCreator(queryString, uri, { ...searchOptions, startOfRange }))
I rejiggered the order of this function to concentrate the `use*` functions towards the top.

2020-10-01 22:21 UTC, mjgiarlo commented on src/components/search/Search.jsx
> +  const defaultUri = 'sinopia'
To name a thing is to imbue it with identity and power.

2020-10-01 22:22 UTC, mjgiarlo commented on src/components/search/Search.jsx
> +                       placeholder="Enter query string"
Placeholder added for consistency w/ template search component.

2020-10-01 22:22 UTC, mjgiarlo commented on src/components/search/Search.jsx
> +                          title="Submit search"
Give it a title so we get hover text that explains the purpose of the icon.

2020-10-01 22:23 UTC, mjgiarlo commented on src/components/search/Search.jsx
> +                          title="Clear query string"
Give it a title so we get hover text that explains the purpose of the icon.

2020-10-01 22:23 UTC, mjgiarlo commented on src/components/search/Search.jsx
> +                            setQueryString('')
Blank the query string in the input field, reset the URI in the dropdown, and ditch the search results.

2020-10-01 22:23 UTC, mjgiarlo commented on src/components/search/Search.jsx
> +                    <FontAwesomeIcon className="trash-icon" icon={faTrashAlt} />
I assume trash icon is OK in this context but happy to use a different FA icon. Cc: @astridu

2020-10-01 22:24 UTC, mjgiarlo commented on src/components/templates/TemplateSearch.jsx
> +  const [queryString, setQueryString] = useState(lastQueryString || '')
Aligning variable names across like components.

2020-10-02 11:22 UTC, justinlittman approved these changes

2020-10-02 11:22 UTC, merged