Set maxwidth for MARC preview.
LD4P/sinopia_editor pull request #2625
Opened 2020-10-07 12:03 UTC by justinlittman

closes #2624

## Why was this change made?
The MARC preview was dropping right, which made it difficult to use.

## How was this change tested?
Locally

## Which documentation and/or configurations were updated?
NA

2020-10-07 12:04 UTC, justinlittman commented
Before:
![image](https://user-images.githubusercontent.com/588335/95328435-8de83a00-0873-11eb-80b4-8fc55617d870.png)

After:
![image](https://user-images.githubusercontent.com/588335/95328530-ad7f6280-0873-11eb-9e0f-8005acbd7ef0.png)

2020-10-07 22:25 UTC, jermnelson requested changes

2020-10-07 22:25 UTC, jermnelson commented on src/components/editor/actions/MarcButton.jsx
> +              marginLeft: '10px', marginRight: '10px', paddingLeft: '10px', paddingRight: '10px', maxWidth: '750px',
This may be better as a CSS class

2020-10-08 13:56 UTC, justinlittman commented on src/components/editor/actions/MarcButton.jsx
> +              marginLeft: '10px', marginRight: '10px', paddingLeft: '10px', paddingRight: '10px', maxWidth: '750px',
In principle, I agree. However, I've been treating the current MARC integration as a proof-of-concept and trying to minimize the entanglement with the rest of the code base, figuring that it will be replaced once we better understand the use case. (This is why MarcButton is a single component.) Thus, in this case I'd recommend that we keep the CSS local rather than adding to the stylesheet.

2020-10-08 14:45 UTC, jermnelson approved these changes

2020-10-08 14:45 UTC, merged