Makes lookup search input and values look better
LD4P/sinopia_editor pull request #2674
Opened 2020-10-09 20:08 UTC by jgreben

## Why was this change made?
Fixes #2640 

## How was this change tested?
N/A only CSS changes were made

2020-10-09 20:35 UTC, justinlittman requested changes
I'm not sure what the desired design was, but:

InputLookup lookup button is now on a separate line (unlike search):
![image](https://user-images.githubusercontent.com/588335/95629027-284fa580-0a4d-11eb-992d-5a5cd5009ef0.png)

The resource templates search is also split onto multiple lines:
![image](https://user-images.githubusercontent.com/588335/95629148-61881580-0a4d-11eb-80f0-b432da5e666d.png)

2020-10-09 20:40 UTC, jgreben commented
Oops, the rebase messed it up..I will push another commit.

2020-10-09 20:55 UTC, jgreben commented
Looks like another PR fixed the problem reported by @astrid, but this PR fixes an issue with the width of the non-nested lookup input and values not matching the containing Div when the browser size is altered.

2020-10-09 22:09 UTC, justinlittman requested changes
Getting closer, but this looks odd:
![image](https://user-images.githubusercontent.com/588335/95635391-4ff93a80-0a5a-11eb-90da-68771dd21cb5.png)

2020-10-12 11:55 UTC, justinlittman approved these changes
Thanks!

2020-10-12 11:55 UTC, merged