Update the close button for Bootstrap 5
LD4P/sinopia_editor pull request #3097
Opened 2021-10-04 19:36 UTC by jcoyne

## Why was this change made?

This is the prescribed way https://getbootstrap.com/docs/5.1/components/close-button/

## How was this change tested?

## Which documentation and/or configurations were updated?

2021-10-04 21:35 UTC, ndushay requested changes
Does this change the appearance of the button at all?  Should @michelleif sign off?  Is this part of an issue?

2021-10-04 22:59 UTC, michelleif commented
i think just the X changed. looks fine and again, i'll double-check in DEV, thank you!

2021-10-05 02:59 UTC, jcoyne commented
@ndushay I attached some screen shots above.

2021-10-05 16:38 UTC, ndushay approved these changes
Thanks for screen shots!

2021-10-05 16:38 UTC, merged